version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.3
executors:
  usaspending-frontend:
    docker:
      - image: 'cimg/node:12.18'
  browser-tools:
    docker:
      - image: cimg/node:15.0.1-browsers
jobs:
  test-app:
    executor:
      name: usaspending-frontend
    parallelism: 3
    steps:
      - checkout
      - node/install-packages
      - run: mkdir ~/junit
      - run: 
          command: |
            TEST=$(circleci tests glob **/__tests__/*-test.{js,jsx} | circleci tests split --split-by=timings)
            npm test $TEST
      - run:
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  lint-app:
    executor:
      name: usaspending-frontend
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  install-chrome:
    executor:
      name: 'browser-tools'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
  lighthouse-performance-audit:
    executor: 
      name: usaspending-frontend
    steps:
      - checkout
      - node/install-packages
      - run: npm run lighthouse
workflows:
  test:
    jobs:
      - test-app
  lint:
    jobs:
      - lint-app
  lighthouse:
    jobs:
      - install-chrome
      - lighthouse-performance-audit